// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_Adminapp_0_H
#define WINRT_Adminapp_0_H
WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::Adminapp
{
    struct IMainPage;
    struct MainPage;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::Adminapp::IMainPage>{ using type = interface_category; };
    template <> struct category<winrt::Adminapp::MainPage>{ using type = class_category; };
    template <> struct category<winrt::Adminapp::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Adminapp::MainPage> = L"Adminapp.MainPage";
    template <> inline constexpr auto& name_v<winrt::Adminapp::XamlMetaDataProvider> = L"Adminapp.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Adminapp::IMainPage> = L"Adminapp.IMainPage";
    template <> inline constexpr guid guid_v<winrt::Adminapp::IMainPage>{ 0xE538C69C,0xE88C,0x5B01,{ 0xB3,0x91,0xAA,0xC2,0x20,0xCA,0x4E,0x61 } }; // E538C69C-E88C-5B01-B391-AAC220CA4E61
    template <> struct default_interface<winrt::Adminapp::MainPage>{ using type = winrt::Adminapp::IMainPage; };
    template <> struct default_interface<winrt::Adminapp::XamlMetaDataProvider>{ using type = winrt::Windows::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::Adminapp::IMainPage>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
        };
    };
    template <typename D>
    struct consume_Adminapp_IMainPage
    {
    };
    template <> struct consume<winrt::Adminapp::IMainPage>
    {
        template <typename D> using type = consume_Adminapp_IMainPage<D>;
    };
}
#endif
