// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230706.1

#pragma once
#ifndef WINRT_Adminapp_H
#define WINRT_Adminapp_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.230706.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.230706.1"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Windows.UI.Xaml.Markup.2.h"
#include "winrt/impl/Adminapp.2.h"
namespace winrt::impl
{
    template <typename D>
    struct produce<D, winrt::Adminapp::IMainPage> : produce_base<D, winrt::Adminapp::IMainPage>
    {
    };
}
WINRT_EXPORT namespace winrt::Adminapp
{
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::Adminapp::IMainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Adminapp::MainPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::Adminapp::XamlMetaDataProvider> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
